control de errores

diff --git a/.github/workflows/Download-images-from-nasa.yml b/.github/workflows/Download-images-from-nasa.yml
--- a/.github/workflows/Download-images-from-nasa.yml
+++ b/.github/workflows/Download-images-from-nasa.yml
@@ -57,12 +57,17 @@ jobs:
         id: fetch_image
         if: ${{ steps.cache-img.outputs.cache-hit != 'true' }}
         run: |
-          echo "Consultando la fecha: ${{ matrix.dates }}"
+          set -e
           response=$(curl -s -X GET "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.dates }}")
+          if [ "$(echo "$response" | jq -r '.error')" != "null" ]; then
+            echo "Error en la consulta: $(echo "$response" | jq -r '.error')" >&2
+            exit 1
+          fi
           image_url=$(echo "$response" | jq -r '.url')
           echo "image_url=$image_url" >> $GITHUB_ENV
           extension="${image_url##*.}"
           echo "image_extension=$extension" >> $GITHUB_ENV
+
 
       - name: Download image from URL 
         if: ${{ steps.cache-img.outputs.cache-hit != 'true' }}
