control

diff --git a/.github/workflows/Download-images-from-nasa.yml b/.github/workflows/Download-images-from-nasa.yml
--- a/.github/workflows/Download-images-from-nasa.yml
+++ b/.github/workflows/Download-images-from-nasa.yml
@@ -63,8 +63,8 @@ jobs:
           image_url=$(echo "$response" | jq -r '.url')
           echo "image_url=$image_url" >> $GITHUB_ENV
           extension="${image_url##*.}"
-          if [ -z "$extension" ]; then
-            echo "Error: La URL no tiene una extensión válida." >&2
+          if [ -z "$extension" ] || ! [[ "$extension" =~ ^(jpg|jpeg|png|gif)$ ]]; then
+            echo "Error: La URL no tiene una extensión válida o es un tipo no soportado." >&2
             exit 1
           fi
           echo "image_extension=$extension" >> $GITHUB_ENV
