adjust

diff --git a/.github/workflows/Download-images-from-nasa.yml b/.github/workflows/Download-images-from-nasa.yml
--- a/.github/workflows/Download-images-from-nasa.yml
+++ b/.github/workflows/Download-images-from-nasa.yml
@@ -59,8 +59,9 @@ jobs:
         run: |
           set -e
           response=$(curl -s -X GET "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.dates }}")
-          if [ "$(echo "$response" | jq -r '.error')" != "null" ]; then
-            echo "Error en la consulta: $(echo "$response" | jq -r '.error')" >&2
+          if echo "$response" | jq -e '.code' > /dev/null; then
+            msg=$(echo "$response" | jq -r '.msg')
+            echo "Error en la consulta: $msg" >&2
             exit 1
           fi
           image_url=$(echo "$response" | jq -r '.url')
@@ -68,9 +69,8 @@ jobs:
           extension="${image_url##*.}"
           echo "image_extension=$extension" >> $GITHUB_ENV
 
-
       - name: Download image from URL 
-        if: ${{ steps.cache-img.outputs.cache-hit != 'true' && success() }}
+        if: ${{ steps.cache-img.outputs.cache-hit != 'true' && steps.fetch_image.outcome == 'success' }}
         uses: minituff/save-image@v1.4
         with:
           url: ${{ env.image_url }}
