updates

diff --git a/.github/workflows/Download-images-from-nasa.yml b/.github/workflows/Download-images-from-nasa.yml
--- a/.github/workflows/Download-images-from-nasa.yml
+++ b/.github/workflows/Download-images-from-nasa.yml
@@ -81,6 +81,12 @@ jobs:
         run: |
           image_url=$(jq -r '.url' response-${{ matrix.dates }}.json)
           echo "image_url=$image_url" >> $GITHUB_ENV
+          extension="${image_url##*.}"
+          if [ -z "$extension" ] || ! [[ "$extension" =~ ^(jpg|jpeg|png|gif)$ ]]; then
+            echo "Error: The URL does not have a valid extension or is an unsupported type" >&2
+            exit 1
+          fi
+          echo "image_extension=$extension" >> $GITHUB_ENV
 
       - name: Download image from url
         uses: minituff/save-image@v1.4
